import type { Carousel } from '../content/schema.js';
import type { Frame } from '../render/frame.js';
import { sha256 } from '../util/fs.js';

const PLACEHOLDER = '<!-- TODO -->';
const STAMP = 'carousel-forge:scaffold';

function bullet(items: string[] | undefined, fallback: string): string {
  if (!items || items.length === 0) return `- ${fallback}`;
  return items.map((item) => `- ${item.startsWith('#') ? item : `#${item}`}`).join('\n');
}

function oneLine(value: string | undefined): string | undefined {
  return value?.replace(/\s*\n\s*/g, ' ').trim() || undefined;
}

/**
 * The mechanical half of the caption work, in its own always-regenerated file.
 *
 * Splitting this out of `caption.md` is deliberate. The outline is derived
 * from `carousel.yaml` and must always match the slides that were just
 * rendered; the caption is written by a human and must never be touched.
 * Those two requirements are in direct conflict inside one file, and the only
 * way to satisfy both there is to merge or refuse on every build. Two files
 * remove the conflict instead of managing it: this one is always safe to
 * clobber, and the other is never clobbered.
 */
export function renderSlideOutline(carousel: Carousel, frames: Frame[]): string {
  const outline = frames.map((frame) => {
    const role = frame.role?.id ?? frame.layout;
    const summary = oneLine(frame.slide.title) ?? oneLine(frame.slide.body) ?? '(no copy)';
    return `${frame.slideNumber}. **${role}** - ${summary}`;
  });

  const ctas = frames
    .map((frame) => oneLine(frame.slide.cta))
    .filter((cta): cta is string => Boolean(cta));

  const lines = [
    '<!--',
    '  Regenerated by `carousel-forge build` on every run. Do not edit.',
    '  Your caption lives in caption.md, which this file never touches.',
    '-->',
    '',
    '# Slide outline',
    '',
    `Theme \`${carousel.theme}\`${carousel.narrative ? ` | narrative \`${carousel.narrative}\`` : ''}`,
    '',
    ...(outline.length > 0 ? outline : ['(no slides)']),
    '',
    '## Call to action',
    '',
    ctas.length > 0 ? ctas.map((cta) => `- ${cta}`).join('\n') : '- (no slide declares a `cta:`)',
    '',
  ];

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n')}\n`;
}

/**
 * A deterministic scaffold for the post caption.
 *
 * This intentionally writes no copy of its own. The CLI has no language model,
 * and template-generated captions read like spam. Everything here is derived
 * mechanically from `carousel.yaml`; an agent following
 * `skills/instagram-carousel/SKILL.md` fills in the blanks.
 */
export function renderCaptionScaffold(carousel: Carousel): string {
  const caption = carousel.caption;
  const handle = carousel.brand?.handle;

  const lines: string[] = [
    '<!--',
    '  Scaffold written by `carousel-forge build`.',
    '  The structure is mechanical; the words are not written for you on purpose.',
    '  Fill in every TODO, then paste the caption into Instagram.',
    '',
    '  Once you edit this file, `build` stops regenerating it and leaves your',
    '  words alone. The slide list lives in slide-outline.md, which is rebuilt',
    '  every run. Use `build --force-caption` to throw this away and start over.',
    '-->',
    '',
    '# Caption',
    '',
    caption?.text?.trim() ||
      `${PLACEHOLDER} write the caption: one hook line, a short payoff, then the CTA.`,
    '',
    '## Hashtags',
    '',
    '### Broad - reach',
    bullet(caption?.hashtags?.broad, `${PLACEHOLDER} 3-5 large tags for the general topic`),
    '',
    '### Niche - relevance',
    bullet(caption?.hashtags?.niche, `${PLACEHOLDER} 8-12 specific tags for this exact audience`),
    '',
    '### Branded',
    bullet(
      caption?.hashtags?.branded,
      handle ? `#${handle.replace(/^@/, '')}` : `${PLACEHOLDER} your own tag`,
    ),
    '',
    '## First comment',
    '',
    caption?.firstComment?.trim() ||
      `${PLACEHOLDER} the first comment is prime real estate - put the link, the long-form context, or a question that invites replies.`,
    '',
  ];

  const body = `${lines.join('\n').replace(/\n{3,}/g, '\n\n')}\n`;
  return `${body}\n<!-- ${STAMP} ${sha256(canonical(body))} -->\n`;
}

/**
 * Trailing blank lines are not content. Normalising them on both sides keeps
 * the stamp from depending on exactly how many newlines sat between the body
 * and the stamp itself.
 */
function canonical(body: string): string {
  return body.replace(/\n+$/, '\n');
}

/**
 * Has a human touched this caption?
 *
 * The scaffold records a hash of its own body, so the common case is an exact
 * answer rather than a guess: if the file still hashes to what was written,
 * nobody has edited it. Files written before the stamp existed, or with the
 * stamp deleted, fall back to asking whether any TODO is still unresolved -
 * which errs toward preserving, because losing someone's writing is far worse
 * than leaving a stale scaffold on disk.
 */
export function captionIsPristine(existing: string): boolean {
  const stamp = new RegExp(`<!--\\s*${STAMP}\\s+([0-9a-f]{64})\\s*-->`).exec(existing);
  if (stamp) {
    return sha256(canonical(existing.slice(0, stamp.index))) === stamp[1];
  }
  return existing.includes(PLACEHOLDER);
}

/** Slide lines that differ between two outlines, for the "your caption may be stale" note. */
export function outlineDelta(before: string, after: string): string[] {
  const slides = (text: string) =>
    new Map(
      [...text.matchAll(/^(\d+)\.\s+(.*)$/gm)].map((m) => [Number(m[1]), (m[2] ?? '').trim()]),
    );
  const a = slides(before);
  const b = slides(after);
  const changed: string[] = [];
  for (const [n, line] of b) {
    if (!a.has(n)) changed.push(`slide ${n} added - ${line}`);
    else if (a.get(n) !== line) changed.push(`slide ${n} changed - ${line}`);
  }
  for (const n of a.keys()) if (!b.has(n)) changed.push(`slide ${n} removed`);
  return changed.sort();
}
